controllers/CourseController.php
<?php

namespace app\controllers;

use app\models\Answer;
use app\models\Faq;
use Yii;
use app\models\Qa;
use app\models\Module;
use app\models\Theme;
use app\models\User;
use app\models\UserAnswer;
use app\models\UserDone;
use app\models\Question;
use Symfony\Component\Finder\Exception\AccessDeniedException;
use yii\helpers\ArrayHelper;
use yii\helpers\VarDumper;
use yii\web\ForbiddenHttpException;
use yii\web\MethodNotAllowedHttpException;
use yii\web\NotFoundHttpException;

class CourseController extends \yii\web\Controller
{

	public function beforeAction($action)
	{
		Module::$userId = \Yii::$app->user->id;
		Theme::$userId = \Yii::$app->user->id;
		return parent::beforeAction($action); // TODO: Change the autogenerated stub
	}

	public function actionIndex()
	{
		$modules = Module::find()->sort()->all();
		/*$user_done = UserDone::find()
            ->where('user_id='.\Yii::$app->user->id.' AND module_id=27')
            ->one();
		$user_answers = UserAnswer::find()
            ->where('user_id='.\Yii::$app->user->id.' AND module_id=27')
            ->all();
		$questions = Question::find()
            ->where('module_id=27')
            ->all();
		foreach ($questions as $question){
            $answer = Answer::find()
                ->where('question_id='.$question->id)
                ->one();

        }
        var_dump($questions[0]);
		exit();*/
        $user_done = UserDone::find()
            ->where('user_id='.\Yii::$app->user->id.' AND module_id=27')
            ->one();
		$pr_task = false;
		if($user_done){
            $pr_task = true;
        }
		return $this->render('index', [
			'modules' => $modules,
            'pr_task' => $pr_task
		]);
	}

	public function actionStudy()
	{
		if ($model = $this->getAwait(true)) {
			if (\Yii::$app->request->isPost) {
				(new UserDone([
					'user_id' => \Yii::$app->user->id,
					'module_id' => $model->module_id,
					'theme_id' => $model->id,
					'count_try' => 1,
				]))->save();
				if ($model->hasQuestions()) {
					return $this->redirect(['qa']);
				} else {
					$next = $this->getAwait(false);
					if ($next instanceof Module) {
						(new UserDone([
							'user_id' => \Yii::$app->user->id,
							'module_id' => $model->module_id,
							'theme_id' => null,
							'count_try' => 1,
						]))->save();
						return $this->redirect(['index']);
					}
					return $this->redirect(['study']);
				}
			}
			return $this->render('study', [
				'theme' => $model,
			]);
		}
		return $this->redirect(['index']);
	}

	public function actionQa()
	{
		if ($model = $this->getAwait(false)) {
			$qa = new Qa();
			$qa->model = $model;
			if ($qa->load(\Yii::$app->request->post()) && $qa->validate()) {
				$qa->saveResult();

				$params = [
					'user_id' => \Yii::$app->user->id,
				];
				if ($model instanceof Module) {
					$params['module_id'] = $model->id;
					$params['theme_id'] = null;
				} elseif ($model instanceof Theme) {
					$params['module_id'] = $model->module_id;
					$params['theme_id'] = $model->id;
				}

				$model = UserDone::find()->where($params)->one();
				if ($model) {
					$model->updateCounters(['count_try' => 1]);
				} else {
					$model = new UserDone(ArrayHelper::merge($params, [
						'count_try' => 1,
					]));
					$model->save();
				}

				$next = $this->getAwait(false);
				if ($next instanceof Module) {
					(new UserDone([
						'user_id' => \Yii::$app->user->id,
						'module_id' => $model->module_id,
						'theme_id' => null,
						'count_try' => 0,
					]))->save();
				}
				return $this->render('result', [
					'model' => $qa->model,
				]);
//				return $this->redirect(['index']);
			}
			
			if ($qa->load(\Yii::$app->request->post())) {
				if ($qa->answers) {
					foreach($qa->answers as $key => $answers) {
						if (!is_array($answers)) {
							$answers_out[$key] = $answers;
						}
					}
					$qa->answers = $answers_out;
				}
			}
			
			return $this->render('qa', [
				'model' => $model,
				'qa' => $qa,
			]);
		}
		return $this->redirect(['index']);
	}

	public function actionTry($module_id, $theme_id = null)
	{
		if (!empty($theme_id)) {
			$model = Theme::findOne([
				'id' => $theme_id,
				'module_id' => $module_id,
			]);
		} else {
			$model = Module::findOne([
				'id' => $module_id,
			]);
		}

		if (!$model) {
			throw new NotFoundHttpException('Тест не найден');
		}

		if (!$model->hasQuestions()) {
			throw new MethodNotAllowedHttpException('Вопросы для данного модуля/темы отсутствуют');
		}

		if (!$model->canGodPermission() && !$model->hasTry()) {
			throw new ForbiddenHttpException('Вы исчерпали все попытки пройти данный тест!');
		}
		$model::$userId = \Yii::$app->user->id;
		$qa = new Qa();
		$qa->model = $model;
		if ($qa->load(\Yii::$app->request->post()) && $qa->validate()) {
			UserAnswer::deleteAll([
				'module_id' => $module_id,
				'theme_id' => !empty($theme_id) ? $theme_id : null,
				'user_id' => \Yii::$app->user->id,
			]);
			$qa->saveResult();
			$model->incrTry();
			if ($model instanceof Module) {
//				$model->checkTestsResult();
			}
			return $this->redirect(['result', 'module_id' => $module_id, 'theme_id' => $theme_id]);
		}
		
		if ($qa->load(\Yii::$app->request->post())) {
			if ($qa->answers) {
				foreach($qa->answers as $key => $answers) {
					if (!is_array($answers)) {
						$answers_out[$key] = $answers;
					}
				}
				$qa->answers = $answers_out;
			}
		}
		
		return $this->render('try', [
			'model' => $model,
			'qa' => $qa,
		]);
	}

	public function actionResult($module_id, $theme_id = null)
	{
		$user_id = Yii::$app->user->id;
		$user = User::findOne(Yii::$app->user->id);
		Module::$userId = $user_id;
		Theme::$userId = $user_id;

		if (!empty($theme_id)) {
			$model = Theme::findOne([
				'id' => $theme_id,
				'module_id' => $module_id,
			]);
			$questions=Question::findAll([
				'theme_id' => $theme_id,
				'module_id' => $module_id,
				]);
		} else {
			$model = Module::findOne([
				'id' => $module_id,
			]);
			$questions=Question::findAll([
				
				'module_id' => $module_id,
				]);
		}

		return $this->render('result', [
			'model' => $model,
			'module' => Module::findOne(['id' => $module_id]),
			'qaBaseModel' => $model,
			'questions'=>$questions,
		]);
	}
	public function actionResult2($module_id, $theme_id = null)
	{
		$user_id = Yii::$app->user->id;
		$user = User::findOne(Yii::$app->user->id);
		Module::$userId = $user_id;
		Theme::$userId = $user_id;

		if (!empty($theme_id)) {
			$model = Theme::findOne([
				'id' => $theme_id,
				'module_id' => $module_id,
			]);
			$questions=Quesiton::findAll([
				'theme_id' => $theme_id,
				'module_id' => $module_id,
				]);
		} else {
			$model = Module::findOne([
				'id' => $module_id,
			]);
			$questions=Quesiton::findAll([
				
				'module_id' => $module_id,
				]);
		}

		return $this->render('result2', [
			'model' => $model,
			'module' => Module::findOne(['id' => $module_id]),
			'questions'=>$questions,
		]);
	}
	public function actionRemind($theme_id)
	{
		$model = Theme::find()->where(['id' => $theme_id])->one();
		/** @var Theme $model */
		if (!$model) {
			throw new NotFoundHttpException('Тема не найдена');
		}
		if (!$model->canGodPermission() && !$model->isChecked()) {
			throw new ForbiddenHttpException('У вас нет доступа к данной теме. Изучите темы в установленном порядке что бы получить доступ для повторного ознакомления.');
		}
		return $this->render('study', [
			'theme' => $model,
			'readOnly' => true,
		]);
	}

	/**
	 * @param bool $themeOnly
	 * @return Module|Theme|null
	 */
	protected function getAwait($themeOnly = true)
	{
		$modules = Module::find()->sort()->all();
		foreach ($modules as $module) {
			if ($module->hasAwait()) {
				foreach ($module->themes as $theme) {
					if ($theme->hasAwait()) {
						if (count($theme->themes) > 0) {
							foreach ($theme->themes as $t) {
								if ($t->hasAwait()) {
									return $t;
								}
							}
						}
						return $theme;
					}
				}
				if (!$themeOnly) {
					if ($module->hasAwait()) {
						return $module;
					}
				}
				continue;
			}
		}
		return null;
	}
}

views/course/_faq_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Faq */
/* @var $form yii\widgets\ActiveForm */
?>


<?php $form = ActiveForm::begin([
	'id' => 'faq-form',
	'action' => '/faq',
	//'options' => ['class' => 'form-horizontal'],
	'fieldConfig' => [
		//'template' => "<div class='field-faq-question required'>{input}</div><div class=\"col-md-12 col-sm-12 col-sm-offset-2 col-md-offset-2\">{error}</div>",
		'template' => "{input}\n<div class='help-block text-center'>{error}</div>",
	],
]); ?>
<input type="hidden" name="url" value="<?= \yii\helpers\Url::to() ?>">
<input type="hidden" name="theme_id" value="<?= $theme_id ?>">
<?= $form->field($model, 'question')->textarea(['rows' => 6, 'placeholder' => 'Задать вопрос по теме']) ?>

<div class="form-group text-center">
	<?= Html::submitButton('Задать вопрос', ['class' => 'btn btn-warning btn-lg load-more']) ?>
</div>
<?php ActiveForm::end(); ?>

views/course/_item.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

?>

<div class="qq-title"><?= $model->question ?></div>
<?php if (!empty($model->answer)): ?>
    <div class="qq-dd well">
        <p><?= $model->answer ?></p>
    </div>
<?php endif; ?>
<br/>

views/course/_qa-field.php
<?php

use yii\bootstrap\Html;

/* @var $this \yii\web\View */
/* @var $question \app\models\Question */
/* @var $qa \app\models\Qa */
/* @var $form \yii\bootstrap\ActiveForm */


$attribute = "answers[$question->id]";
$items = $question->answersList;
$label = nl2br($question->title);
$options = [];
$error = '';
Html::addCssClass($options, 'form-group well');
if ($qa->hasErrors($attribute)) {
    Html::addCssClass($options, 'has-error');
    $error = $qa->getFirstError($attribute);
}
$this->registerCss(<<<CSS
.well {
    margin-bottom: 20px !important;
}
.question-title {
    margin-top: 0;
}
.has-error .question-title  {
    color: #a94442;
}
legend {
    font-size: 16px; 
    font-weight: bold;
    margin-bottom: 10px;
    margin-top: 20px;
}
.radio, .checkbox {
    margin-top: 0;
    margin-bottom: 0;
}
.form-group {
    margin-bottom: 0;
}
.radio .help-block, .checkbox .help-block {
    display: none;
}
CSS
    , [], 'qa-error');

?>

<?= Html::beginTag('div', $options); ?>
<h4 class="question-title"><?= $label ?></h4>
<?php if ($question->multipleTrueAnswers()): ?>
    <?php //= $form->field($qa, $attribute)->checkboxList($items)->label($label)->hint($error) ?>
    <?= Html::activeHiddenInput($qa, $attribute); ?>
    <fieldset class="<?= $current ? 'current' : '' ?>">

        <?php
        $j = 0;
        $len = count($question->answers);
        $g = 1;
        ?>
        <?php foreach ($question->answers as $i => $answer): ?>

            <?php if ($answer->isDelimiter()): ?>
                <?php
                if ($j != 0) {
                    echo '</span>';
                    $g = 1;
                }
                if ($g == 1) {
                    $g = 0;
                    echo '<span class="sub_question">';
                }
                ?>
                <legend class='legend_<?= $i ?>'
                        style="font-size: 16px; font-weight: bold;"><?= $answer->title ?></legend>
            <?php else: ?>
                <?php

                if ($g == 1) {
                    $g = 0;
                    echo '<span class="sub_question">';
                }
                ?>
                <?= $form->field($qa, $attribute . '[]')->checkbox(['class' => 'input_checkbox', 'value' => $answer->id, 'uncheck' => true])->label($answer->title, ['for' => false]) ?>
            <?php endif; ?>

            <?php
            if ($j == $len - 1) {
                echo '</span>';
            }
            $j++;

            ?>

        <?php endforeach; ?>
    </fieldset>
<?php else: ?>
    <?php //= $form->field($qa, $attribute)->radioList($items)->label($label)->hint($error) ?>
    <fieldset class="<?= $current ? 'current' : '' ?>">
        <?= Html::activeHiddenInput($qa, $attribute); ?>
        <?php foreach ($question->answers as $i => $answer): ?>
            <?php if ($answer->isDelimiter()): ?>
                <legend style="font-size: 16px; font-weight: bold;"><?= $answer->title ?></legend>
            <?php else: ?>
                <?= $form->field($qa, $attribute)->radio(['class' => 'input_radio', 'value' => $answer->id, 'uncheck' => false])->label($answer->title, ['for' => false]) ?>
            <?php endif; ?>
        <?php endforeach; ?>
    </fieldset>
<?php endif; ?>

<?php if ($error): ?>
    <p class="help-block"><?= $error ?></p>
<?php endif; ?>
<?= Html::endTag('div'); ?>

views/course/_review-alert.php
<?php

use app\models\User;
use yii\helpers\Html;

/** @var \app\models\User $user */
/** @var boolean $show */

$user = Yii::$app->user->identity;
$show = ($show || $user->review === User::REVIEW_AWAIT) && $user->review != User::REVIEW_SEND;

?>

<?php if ($show): ?>
<div class="alert alert-info">
    <h5>Оставьте пожалуйста отзыв о курсе!</h5>
    <?= Html::a('Оставить отзыв', ['/site/review'], ['class' => 'btn btn-success btn-fill']) ?>
</div>
<?php endif; ?>

views/course/qa.php
<?php

use yii\bootstrap\Html;
use yii\bootstrap\ActiveForm;
use app\models\Module;
use app\models\Theme;

/* @var $this yii\web\View */
/* @var $model Module|Theme */
/* @var $qa \app\models\Qa */

?>


<h1>Тестирование</h1>
<?php if ($model instanceof Module): ?>
    <h2><?= $model->title ?></h2>
<?php elseif ($model instanceof Theme): ?>
    <h2><?= $model->module->title ?></h2>
    <h3><?= $model->title ?></h3>
<?php endif; ?>
<?php if (!empty($model->test_title)): ?>
    <h3 class="text-primary"><?= $model->test_title ?></h3>
<?php endif ?>
<div class="">
    <hr>
    <?php $form = ActiveForm::begin(['method' => 'post']); ?>
        <?php foreach ($model->questions as $question): ?>
            <?= $this->render('_qa-field', ['question' => $question, 'qa' => $qa, 'form' => $form]); ?>
            <hr>
        <?php endforeach; ?>
        <?= Html::submitButton('Закончить тестирование', ['class' => 'btn btn-primary btn-lg btn-block']) ?>
    <?php ActiveForm::end(); ?>
</div>

<!--<a href="--><?//= Url::to(['qa']) ?><!--" class="btn btn-primary btn-lg btn-block">Закончить тестирование</a>-->

views/course/result.php
<?php
//use Yii;
use yii\helpers\Url;
use app\assets\CourseAsset;
use app\models\Module;
use app\models\Qa;
use yii\widgets\Pjax;
use app\models\Answer;
use app\models\UserAnswer;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $modules Module[] */
/* @var $model app\models\Module|app\models\Theme */

CourseAsset::register($this);

?>

<!-- <div class="row">
    <div class="col-md-12">
		<?php if ($model): ?>
			<?= $this->render('result/_qa', ['qa' => Qa::loadPrevResults($model), 'model' => $model]); ?>
		<?php endif; ?>
		<?php if (!empty($model->test_comment_after)): ?>
			<div class="well">
				<?= $model->test_comment_after; ?>
			</div>
		<?php endif; ?>
    </div>

</div> -->
<div class="row">
	<div class="col-md-12">
		<h1><?=$model->title?></h1>
		<h3></h3>
		<?php if (isset($questions)) { ?>
        <?php foreach ($questions as $question):?>
            <h3><?= $question->title; ?></h3>
            <?php

                $isMultiple=$question->multipleTrueAnswers();
                $trueAnswers=$question->getTrueAnswers();
                $userAnswers=UserAnswer::findAll([
                    'user_id'=>Yii::$app->user->id,
                    'module_id'=>$question->module_id,
                    'theme_id'=>$question->theme_id,
                    'question_id'=>$question->id,
                ]);
                $userAnsws=array();
            foreach ($userAnswers as $userAnswer) {
                    array_push($userAnsws,$userAnswer->answer_id);
                }

                $isTrue=UserAnswer::isTrue($userAnsws,$trueAnswers);

                if($isTrue==1) {
                    $class = "alert alert-success";
                    $phrase="Вы правильно ответили на вопрос";
                }
                elseif($isTrue==0){
                    $class = "alert alert-danger";
                    $phrase="Вы не правильно ответили на вопрос";
                }
                elseif($isTrue==2){
                    $class = "alert alert-info";
                    $phrase="Вы ответили на вопрос правильно частично";
                }
                if(!$isMultiple):
                    $id=$trueAnswers[0];
                    $ans=Answer::findOne($id);
					if (isset($userAnsws[0])) {
						$id=$userAnsws[0];
						$usAnsw=Answer::findOne($id);
						//echo $ans->title;
						?>
						<div class="<?= $class ?>">
							<p>Правильный ответ: <?= $ans->title ?></p>
							<p>Вы ответили <?=$usAnsw->title ?></p>
							<p><?= $phrase ?></p>
							<div class="addition">
								<p><?=$question->comment_after?></p>
								<?php if($question->file != ""): ?><a href="<?= $question->file; ?>">Скачать файл к тесту</a><?php endif; ?>
							</div>
						</div>
					<?php } ?>
                <?php else: ?>
                    <?php $count=count($question->answers); ?>
                    <?php $metka=0; ?>
                    <?php $ansArray=array();?>
                    <?php $blockAllAnswers=array();?>
                    <?php $blockUserAnswers=array();?>
                    <?php foreach ($question->answers as $answer):?>
                        <?php
                            $metka++;
                            if(($answer->is_true==-1)&&(count($ansArray)==0)){?>
                                <p><?= $answer->title ?></p>

                            <?php
                                continue;
                            }
                            if($answer->is_true==-1){
                                echo UserAnswer::generateMultipleBlock($userAnsws,$ansArray,$question,$blockUserAnswers);
                                ?><p><?= $answer->title ?></p><?php
                                $ansArray=array();
                                $blockAllAnswers=array();
                                $blockUserAnswers=array();
                                continue;
                            }
                            array_push($blockAllAnswers,$answer->id);
                            $blockUserAnswers=array_intersect($userAnsws,$blockAllAnswers);
                            if($answer->is_true==1){
                                array_push($ansArray, $answer->id);
                            }

                            if($metka==$count) {

                                echo UserAnswer::generateMultipleBlock($userAnsws,$ansArray,$question,$blockUserAnswers);
                                $string= '<div class="addition-delimiter">';
                                $string.=$question->comment_after;
                                $string.=($question->file!="")? '<a href="'.$question->file.'">Скачать файл к тесту</a>': '';
                                $string.= '</div><br>';
                                echo $string;
                                continue;
                            }

                        ?>
                    <?php endforeach;?>
                <?php endif; ?>
        <?php  endforeach; ?>



		<?php /*foreach ($questions as $question):*/?><!--
			<?php
/*				$isMultiple=0;
				$answers=Answer::findAll([
					'question_id'=>$question->id,
					'is_true'=>[-1,1],
				]);
				$correctAnswers=array();
				$usAnswers=array();
				$isCorrect=0;
				$userAnswers=UserAnswer::findAll([
					'user_id'=>Yii::$app->user->id,
					'module_id'=>$question->module_id,
					'theme_id'=>$question->theme_id,
					'question_id'=>$question->id,
				]);
				if(count($answers)>1){
					$isMultiple=1;
				}
				if($isMultiple){
					foreach ($answers as $answ) {
					# code...
					array_push($correctAnswers, $answ->id);
					}
					foreach ($userAnswers as $usansw) {
					# code...
					array_push($usAnswers, $usansw->answer_id);
					}
					$result=array_intersect($usAnswers, $correctAnswers);

					if (count($result)==count($usAnswers)){
						$isCorrect=1;
					}
					elseif (count($result)==0) {
						# code...
						$isCorrect=0;
					}
					else{
						$isCorrect=2;
					}
				}
				else{
					if($userAnswers[0]->answer_id==$answers[0]->id){
						$isCorrect=1;
					}
				}

			*/?>
			<p><?/*=$question->title*/?></p>
			<?php /*if($isCorrect==0):*/?>
				<div class="alert alert-danger">
					<?php /*if($isMultiple): */?>
						<p>Правильные ответы:<br>
						<?php /*foreach ($answers as $ans):*/?>
							<?/*=$ans->title*/?><br>
						<?php /*endforeach;*/?>

						</p>
					<?php /*else: */?>
						<p>
							Правильный ответ: <?/*=$answers[0]->title*/?>
						</p>
					<?php /*endif;*/?>
					<p></p>
					<p>Вы не правильно ответили на вопрос</p>
					<p><?/*=$question->comment_after*/?></p>
				</div>
			<?php /*elseif($isCorrect==1):*/?>
				<div class="alert alert-success">
					<?php /*if($isMultiple): */?>
						<p>Правильные ответы:<br>
						<?php /*foreach ($answers as $ans):*/?>
							<?/*=$ans->title*/?><br>
						<?php /*endforeach;*/?>

						</p>
					<?php /*else: */?>
						<p>
							Правильный ответ: <?/*=$answers[0]->title*/?>
						</p>
					<?php /*endif;*/?>
					<p></p>
					<p>Вы правильно ответили на вопрос</p>
					<p><?/*=$question->comment_after*/?></p>
				</div>
			<?php /*elseif($isCorrect==2):*/?>
				<div class="alert alert-info">
					<?php /*if($isMultiple): */?>
						<p>Правильные ответы:<br>
						<?php /*foreach ($answers as $ans):*/?>
							<?/*=$ans->title*/?><br>
						<?php /*endforeach;*/?>

						</p>
					<?php /*else: */?>
						<p>
							Правильный ответ: <?/*=$answers[0]->title*/?>
						</p>
					<?php /*endif;*/?>
					<p></p>
					<p>Вы ответили на вопрос правильно частично</p>
					<p><?/*=$question->comment_after*/?></p>
				</div>
			<?php /*endif;*/?>
		--><?php /*endforeach; */?>
		<?php } ?>
	</div>
</div>
<div class="row">
	<div class="col-lg-12" style="text-align: center">
		<?= Html::a('Продолжить обучение',['/course/index'],['class'=>'btn btn-primary']) ?>
	</div>
</div>

views/course/result2.php
<?php

use yii\helpers\Url;
use app\assets\CourseAsset;
use app\models\Module;
use app\models\Qa;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $modules Module[] */
/* @var $model app\models\Module|app\models\Theme */

CourseAsset::register($this);

?>
<div class="row">
    <div class="col-md-12">
		
    </div>

</div>

views/course/study.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\widgets\Menu;
use app\models\ThemeFile;

/* @var $this yii\web\View */
/* @var $theme \app\models\Theme */
/* @var $readOnly null|boolean */

$readOnly = isset($readOnly) ? $readOnly : false;

//$this->title = $theme->module->title . '/' . $theme->title;
//$this->params['breadcrumbs'][] = ['label' => 'Курс', 'url' => ['index']];
//$this->params['breadcrumbs'][] = $theme->module->title;
//$this->params['breadcrumbs'][] = $theme->title;

?>
<?php

foreach (Yii::$app->session->getAllFlashes() as $status => $message) {
	if ($status == 'success') {
		echo '<div class="alert alert-success" role="alert">' . $message . '</div>';
	}
}

?>

<h1><?= $theme->module->title ?></h1>
<?php if ($parent = $theme->parent): ?>
	<h3><?= $parent->title ?></h3>
	<h4><?= $theme->title ?></h4>
<?php else: ?>
	<h3><?= $theme->title ?></h3>
<?php endif; ?>
<div>
	<?= $theme->getVideo() ?>
</div>
<div class="well">
	<?= $theme->description ?>
</div>
<div>
	<?php foreach (ThemeFile::typeList() as $type => $label): ?>
		<?php if ($files = $theme->filesByType($type)): ?>
            <h3><?= $label ?></h3>
			<?= Menu::widget([
				'items' => array_map(function ($file) {
					/** @var \app\models\ThemeFile $file */
					return [
						'label' => $file->name,
						'url' => $file->file->url,
					];
				}, $theme->filesByType($type)),
			]); ?>
		<?php endif; ?>
	<?php endforeach; ?>
</div>
<?php if ($readOnly !== true): ?>
	<?php $form = ActiveForm::begin(['method' => 'post']); ?>
	<?php if (count($theme->questions) > 0): ?>
		<?= Html::submitButton('Пройти тестирование', ['class' => 'btn btn-primary btn-lg btn-block']) ?>
	<?php else: ?>
		<?= Html::submitButton('Перейти к следующей теме', ['class' => 'btn btn-primary btn-lg btn-block']) ?>
	<?php endif; ?>
	<?php ActiveForm::end(); ?>
<?php elseif ($theme->getResult() < 100 && $theme->hasTry()): ?>
    <a href="<?= Url::to(['course/try', 'module_id' => $theme->module_id, 'theme_id' => $theme->id]); ?>" class="btn btn-success btn-block btn-lg">Пройти тест еще раз</a>
<?php endif; ?>

<?= \yii\widgets\ListView::widget([
	'dataProvider' => new \yii\data\ActiveDataProvider([
		'query' => \app\models\Faq::find()->where(['theme_id'=>$theme->id]),
	]),
	'layout' => "{summary}\n{items}",
	'itemView' => '_item',
	'options' => ['class'=>'col-md-12 col-sm-12', 'tag' => 'div',],
	'itemOptions' => ['class'=>'qq-item'],
	'summary' => '',
	'pager' => [
		'options'=>['class'=>'pager'],   // set clas name used in ui list of pagination
		'prevPageLabel' => 'Previous',   // Set the label for the "previous" page button
		'nextPageLabel' => 'Next',   // Set the label for the "next" page button
		'firstPageLabel'=>'First',   // Set the label for the "first" page button
		'lastPageLabel'=>'Last',    // Set the label for the "last" page button
		'nextPageCssClass'=>'next',    // Set CSS class for the "next" page button
		'prevPageCssClass'=>'prev',    // Set CSS class for the "previous" page button
		'firstPageCssClass'=>'first',    // Set CSS class for the "first" page button
		'lastPageCssClass'=>'last',    // Set CSS class for the "last" page button
		'maxButtonCount'=>10,    // Set maximum number of page buttons that can be displayed
	],
]);
?>

<?= $this->render('_faq_form', [
	'model' => new \app\models\Faq(),
	'theme_id' => $theme->id
]); ?>